- name: backend setup
  hosts: all
  become: yes
  tasks:
    - name: install nodejs repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: create application user
      ansible.builtin.user:
        name: expense-user
        comment: expense-user application

    - name: remove content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create directory
      ansible.builtin.path:
        path: /path
        state: directory

    - name: download code and unarchive
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      ansible.builtin.shell: npm install

    - name: copy backend service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: restart backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes
    
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql
        state: installed

    - name: load schema
      ansible.builtin.shell: mysql -h mysql.sriharsha.shop -uroot -pSriharsha@1 < /app/schema/backend.sql
