    - name: install nodejs repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: create application user
      ansible.builtin.user:
        name: expense

    - name: import role
      ansible.builtin.import_role:
        name: common
        tasks_from: app_prereq

    - name: install dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: copy backend service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: start backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes
    
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql
        state: installed

    - name: load schema
      ansible.builtin.shell: mysql -h mysql.sriharsha.shop -uroot -pSriharsha@1 < /app/schema/backend.sql